### ISSUE TITLE
Don't mount file for dfwfw.conf

### ISSUE THREAD

**Issue by rlanore** [irsl/dfwfw#4]
when you use some tool like 'vi' to update the file. Inode is changed and container don't show modification

Mount directory instead

**Comment by irsl** [comment]
I prefer mounting the directory holding the config file(s), too. This is the reason why the script is looking for the config file in the directory /etc/dfwfw (instead of the original file location /etc/dfwfw.conf). This was introduced via part of the commit
https://github.com/irsl/dfwfw/commit/4e05ca090d2e308d9f1a27bda2e5a2cd7ea9bac4

**Comment by irsl** [comment]
Documentation is updated. Thank you for the recommendation.
